"""Added initial tables

Revision ID: 12cd971c3582
Revises: fee3accad270
Create Date: 2020-04-06 19:32:06.338044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cd971c3582'
down_revision = 'fee3accad270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
