"""Added initial tables

Revision ID: 687b719d2637
Revises: 564c1949e97e
Create Date: 2020-04-06 17:18:42.005659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687b719d2637'
down_revision = '564c1949e97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
